baseURL = "http://paydata.org/"
languageCode = "en-gb"
title = "paydata.org"
theme = "docsy"

# Seem to be broken right now
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# ref: https://github.com/google/docsy-example/blob/master/config.toml


# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"      

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"


[params]
copyright = "Richard Gaywood"


# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false



