baseURL = "https://paydata.org/"
languageCode = "en"
title = "paydata.org"
# theme = "docsy"

# Seem to be broken right now
# disableKinds = ["taxonomy"]


[outputs]
	section = [ "HTML", "RSS", "print" ]

# ref: https://github.com/google/docsy-example/blob/master/config.toml


# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"      

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Will give values to .Lastmod etc.
enableGitInfo = false

[services]
[services.googleAnalytics]
id = "UA-172322811-1"

[params]
copyright = "Richard Gaywood"

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = false
ul_show = 1
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/PenLlawen"
	icon = "fab fa-twitter"
        desc = "Find me on Twitter"
[[params.links.user]]
	name ="Reddit"
	url = "https://www.reddit.com/user/penllawen"
	icon = "fab fa-reddit"
        desc = "Find me on Reddit"
[[params.links.user]]
	name ="Discord"
	url = "https://discordapp.com/users/459741920370098176"
	icon = "fab fa-discord"
        desc = "Find me on Discord"		

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["categories", "tags"] 
# if used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Categories", "Tags"]
# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags"] 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/richardgaywood/blog"
# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "paydata.org"

[module]
proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"	
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

[related]
    threshold = 0 
    includeNewer = true
    toLower = false
    [[related.indices]]
        name = "categories"
        weight = 100
    [[related.indices]]
        name = "tags"
        weight = 75
