[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"

[context.production.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
